language: node_js
node_js: node
services:
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: Fa3y1h/4KOM9O7voI1IUsWKVas/M7sZ+ssuuH1dL0FaYmesM/0T/ZFNgiYnB0HwLUCmML26z0i38/qrZtopWOXcu5NaX6l8S/uS2I3sFs18sC/+4QaLBmuRC2IqtZlgR49f8JuxLYASznPBXoLDrcPaS6vk/c7KQocUS258Cx5fROxNSNLfOH8fpe/aZYfK39oYECx4rJkNDxxFX3K+RVyaX7hRPkHIPUQp9E5cP+55SgYyIPv/msbzAnp+Ld3TznPlJ+mU2ICGixTA0aq9fzw1FRiux96GYcHbETAifjwblX6o+QRqbGr2X7HjlMx1AD3ZqstCrn611ztRx0sIL1wMhfXnA+DGeG56rT0rgxfX3iFTn6CJPlATaZT17OxfmMyragqH2uelNdyDl7EHCckl3DNsHtzltcdoJo0tYPXacNssAc4mvSAgqiMt0yu60JD3Tzjc+Cjbw+U4VL3rLwhJ/KydVccHuV5Zca0oLVuXq1V95f4z2VlZWPNK1wAPt0kOoY+/IKuVBMD+ZhrA9UuCWzV90tqmqaGQZEpFywZ2xHaaBVuN4vJZIoYAZxSxSbWbr00Hg81bWtxqcguubFXxqigMTe/zaF2/oXbC+kRF9w6CIOsi+kwQ4Yg03/g4bzazFFjRd2YSF5WXDO82VXnXS9WArv4NB97z704JvWnY=
  app: watch-this
  on:
    repo: steve2482/watch-this
